name: Build, Analyze, and Scans

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build, Analyze, and Scan
    runs-on: [self-hosted, myntra]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -------------------------
      # SonarQube Scan
      # -------------------------
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # -------------------------
      # NPM Install
      # -------------------------
      - name: Install dependencies
        run: npm install

      # -------------------------
      # Docker Login
      # -------------------------
      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # -------------------------
      # Docker Scout (Filesystem)
      # -------------------------
      - name: Docker Scout FS Scan
        run: |
          docker-scout quickview fs://.
          docker-scout cves fs://.

      # -------------------------
      # Docker Build & Push
      # -------------------------
      - name: Build and Push Docker Image
        run: |
          docker build -t myntra .
          docker tag myntra 22030083/myntra:latest
          docker push 22030083/myntra:latest

      # -------------------------
      # Docker Scout (Image)
      # -------------------------
      - name: Docker Scout Image Scan
        run: |
          docker-scout quickview 22030083/myntra:latest
          docker-scout cves 22030083/myntra:latest
